// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat_sessions.sql

package chatdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChatSession = `-- name: CreateChatSession :one
INSERT INTO chat_sessions (session_id, ip_hash)
VALUES ($1, $2)
ON CONFLICT (session_id) DO UPDATE
SET session_id = EXCLUDED.session_id
RETURNING id, session_id, ip_hash, messages, created_at, last_message_at
`

type CreateChatSessionParams struct {
	SessionID string      `json:"session_id"`
	IpHash    pgtype.Text `json:"ip_hash"`
}

func (q *Queries) CreateChatSession(ctx context.Context, arg CreateChatSessionParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, createChatSession, arg.SessionID, arg.IpHash)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.IpHash,
		&i.Messages,
		&i.CreatedAt,
		&i.LastMessageAt,
	)
	return i, err
}

const getChatSession = `-- name: GetChatSession :one
SELECT id, session_id, ip_hash, messages, created_at, last_message_at
FROM chat_sessions
WHERE session_id = $1
`

func (q *Queries) GetChatSession(ctx context.Context, sessionID string) (ChatSession, error) {
	row := q.db.QueryRow(ctx, getChatSession, sessionID)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.IpHash,
		&i.Messages,
		&i.CreatedAt,
		&i.LastMessageAt,
	)
	return i, err
}

const listChatSessionsByIP = `-- name: ListChatSessionsByIP :many
SELECT id, session_id, ip_hash, messages, created_at, last_message_at
FROM chat_sessions
WHERE ip_hash = $1
ORDER BY last_message_at DESC NULLS LAST, created_at DESC
LIMIT $2
`

type ListChatSessionsByIPParams struct {
	IpHash pgtype.Text `json:"ip_hash"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListChatSessionsByIP(ctx context.Context, arg ListChatSessionsByIPParams) ([]ChatSession, error) {
	rows, err := q.db.Query(ctx, listChatSessionsByIP, arg.IpHash, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatSession{}
	for rows.Next() {
		var i ChatSession
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.IpHash,
			&i.Messages,
			&i.CreatedAt,
			&i.LastMessageAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChatMessages = `-- name: UpdateChatMessages :exec
UPDATE chat_sessions
SET messages = $2,
    last_message_at = NOW()
WHERE session_id = $1
`

type UpdateChatMessagesParams struct {
	SessionID string `json:"session_id"`
	Messages  []byte `json:"messages"`
}

func (q *Queries) UpdateChatMessages(ctx context.Context, arg UpdateChatMessagesParams) error {
	_, err := q.db.Exec(ctx, updateChatMessages, arg.SessionID, arg.Messages)
	return err
}
