// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package chatdb

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type JobStatus string

const (
	JobStatusPending    JobStatus = "pending"
	JobStatusProcessing JobStatus = "processing"
	JobStatusCompleted  JobStatus = "completed"
	JobStatusFailed     JobStatus = "failed"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus `json:"job_status"`
	Valid     bool      `json:"valid"` // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

type CacheKey struct {
	ID        pgtype.UUID        `json:"id"`
	Key       string             `json:"key"`
	Data      []byte             `json:"data"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ChatSession struct {
	ID            pgtype.UUID        `json:"id"`
	SessionID     string             `json:"session_id"`
	IpHash        pgtype.Text        `json:"ip_hash"`
	Messages      []byte             `json:"messages"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
}

type EmbeddingJob struct {
	ID              pgtype.UUID        `json:"id"`
	PostID          pgtype.UUID        `json:"post_id"`
	Status          JobStatus          `json:"status"`
	Error           pgtype.Text        `json:"error"`
	ChunksTotal     pgtype.Int4        `json:"chunks_total"`
	ChunksCompleted pgtype.Int4        `json:"chunks_completed"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

type Post struct {
	ID              pgtype.UUID        `json:"id"`
	Slug            string             `json:"slug"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	ContentUrl      string             `json:"content_url"`
	Categories      []string           `json:"categories"`
	Tags            []string           `json:"tags"`
	Featured        pgtype.Bool        `json:"featured"`
	ViewCount       pgtype.Int4        `json:"view_count"`
	ReadTimeMinutes pgtype.Int4        `json:"read_time_minutes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	IsArchived      pgtype.Bool        `json:"is_archived"`
}

type PostEmbedding struct {
	ID         pgtype.UUID        `json:"id"`
	PostID     pgtype.UUID        `json:"post_id"`
	ChunkIndex int32              `json:"chunk_index"`
	Embedding  pgvector.Vector    `json:"embedding"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type RateLimit struct {
	ID           pgtype.UUID        `json:"id"`
	IpHash       string             `json:"ip_hash"`
	Endpoint     string             `json:"endpoint"`
	RequestCount pgtype.Int4        `json:"request_count"`
	WindowStart  pgtype.Timestamptz `json:"window_start"`
}

type ViewEvent struct {
	ID        pgtype.UUID        `json:"id"`
	PostID    pgtype.UUID        `json:"post_id"`
	IpHash    pgtype.Text        `json:"ip_hash"`
	UserAgent pgtype.Text        `json:"user_agent"`
	Referrer  pgtype.Text        `json:"referrer"`
	ViewedAt  pgtype.Timestamptz `json:"viewed_at"`
}
