// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package postdb

import (
	"context"
)

// iteratorForCreateEmbeddings implements pgx.CopyFromSource.
type iteratorForCreateEmbeddings struct {
	rows                 []CreateEmbeddingsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateEmbeddings) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateEmbeddings) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].PostID,
		r.rows[0].ChunkIndex,
		r.rows[0].ChunkText,
		r.rows[0].Embedding,
	}, nil
}

func (r iteratorForCreateEmbeddings) Err() error {
	return nil
}

func (q *Queries) CreateEmbeddings(ctx context.Context, arg []CreateEmbeddingsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"post_embeddings"}, []string{"post_id", "chunk_index", "chunk_text", "embedding"}, &iteratorForCreateEmbeddings{rows: arg})
}
