// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: embeddings.sql

package postdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const createEmbedding = `-- name: CreateEmbedding :one
INSERT INTO post_embeddings (
  post_id, chunk_index, chunk_text, embedding
) VALUES (
  $1, $2, $3, $4
) RETURNING id, post_id, chunk_index, chunk_text, embedding, created_at
`

type CreateEmbeddingParams struct {
	PostID     pgtype.UUID     `json:"post_id"`
	ChunkIndex int32           `json:"chunk_index"`
	ChunkText  string          `json:"chunk_text"`
	Embedding  pgvector.Vector `json:"embedding"`
}

func (q *Queries) CreateEmbedding(ctx context.Context, arg CreateEmbeddingParams) (PostEmbedding, error) {
	row := q.db.QueryRow(ctx, createEmbedding,
		arg.PostID,
		arg.ChunkIndex,
		arg.ChunkText,
		arg.Embedding,
	)
	var i PostEmbedding
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ChunkIndex,
		&i.ChunkText,
		&i.Embedding,
		&i.CreatedAt,
	)
	return i, err
}

type CreateEmbeddingsParams struct {
	PostID     pgtype.UUID     `json:"post_id"`
	ChunkIndex int32           `json:"chunk_index"`
	ChunkText  string          `json:"chunk_text"`
	Embedding  pgvector.Vector `json:"embedding"`
}

const deleteEmbeddingsByPostID = `-- name: DeleteEmbeddingsByPostID :exec
DELETE FROM post_embeddings WHERE post_id = $1
`

func (q *Queries) DeleteEmbeddingsByPostID(ctx context.Context, postID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmbeddingsByPostID, postID)
	return err
}

const getEmbeddingByID = `-- name: GetEmbeddingByID :one
SELECT id, post_id, chunk_index, chunk_text, embedding
FROM post_embeddings
WHERE id = $1
`

type GetEmbeddingByIDRow struct {
	ID         pgtype.UUID     `json:"id"`
	PostID     pgtype.UUID     `json:"post_id"`
	ChunkIndex int32           `json:"chunk_index"`
	ChunkText  string          `json:"chunk_text"`
	Embedding  pgvector.Vector `json:"embedding"`
}

func (q *Queries) GetEmbeddingByID(ctx context.Context, id pgtype.UUID) (GetEmbeddingByIDRow, error) {
	row := q.db.QueryRow(ctx, getEmbeddingByID, id)
	var i GetEmbeddingByIDRow
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ChunkIndex,
		&i.ChunkText,
		&i.Embedding,
	)
	return i, err
}

const getEmbeddingsByPostID = `-- name: GetEmbeddingsByPostID :many
SELECT id, post_id, chunk_index, chunk_text, embedding
FROM post_embeddings
WHERE post_id = $1
ORDER BY chunk_index
`

type GetEmbeddingsByPostIDRow struct {
	ID         pgtype.UUID     `json:"id"`
	PostID     pgtype.UUID     `json:"post_id"`
	ChunkIndex int32           `json:"chunk_index"`
	ChunkText  string          `json:"chunk_text"`
	Embedding  pgvector.Vector `json:"embedding"`
}

func (q *Queries) GetEmbeddingsByPostID(ctx context.Context, postID pgtype.UUID) ([]GetEmbeddingsByPostIDRow, error) {
	rows, err := q.db.Query(ctx, getEmbeddingsByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEmbeddingsByPostIDRow{}
	for rows.Next() {
		var i GetEmbeddingsByPostIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ChunkIndex,
			&i.ChunkText,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSimilarEmbeddings = `-- name: SearchSimilarEmbeddings :many
SELECT 
  e.id,
  e.post_id,
  e.chunk_index,
  e.chunk_text,
  e.embedding,
  p.slug,
  p.title,
  p.description,
  1 - (e.embedding <=> $1) as similarity
FROM post_embeddings e
JOIN posts p ON p.id = e.post_id
WHERE p.is_archived = false AND p.published_at IS NOT NULL
ORDER BY e.embedding <=> $1
LIMIT $2
`

type SearchSimilarEmbeddingsParams struct {
	Embedding pgvector.Vector `json:"embedding"`
	Limit     int32           `json:"limit"`
}

type SearchSimilarEmbeddingsRow struct {
	ID          pgtype.UUID     `json:"id"`
	PostID      pgtype.UUID     `json:"post_id"`
	ChunkIndex  int32           `json:"chunk_index"`
	ChunkText   string          `json:"chunk_text"`
	Embedding   pgvector.Vector `json:"embedding"`
	Slug        string          `json:"slug"`
	Title       string          `json:"title"`
	Description pgtype.Text     `json:"description"`
	Similarity  int32           `json:"similarity"`
}

func (q *Queries) SearchSimilarEmbeddings(ctx context.Context, arg SearchSimilarEmbeddingsParams) ([]SearchSimilarEmbeddingsRow, error) {
	rows, err := q.db.Query(ctx, searchSimilarEmbeddings, arg.Embedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchSimilarEmbeddingsRow{}
	for rows.Next() {
		var i SearchSimilarEmbeddingsRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ChunkIndex,
			&i.ChunkText,
			&i.Embedding,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSimilarEmbeddingsByCategory = `-- name: SearchSimilarEmbeddingsByCategory :many
SELECT 
  e.id,
  e.post_id,
  e.chunk_index,
  e.chunk_text,
  e.embedding,
  p.slug,
  p.title,
  p.description,
  1 - (e.embedding <=> $1) as similarity
FROM post_embeddings e
JOIN posts p ON p.id = e.post_id
WHERE p.is_archived = false 
  AND p.published_at IS NOT NULL
  AND $2 = ANY(p.categories)
ORDER BY e.embedding <=> $1
LIMIT $3
`

type SearchSimilarEmbeddingsByCategoryParams struct {
	Embedding  pgvector.Vector `json:"embedding"`
	Categories []string        `json:"categories"`
	Limit      int32           `json:"limit"`
}

type SearchSimilarEmbeddingsByCategoryRow struct {
	ID          pgtype.UUID     `json:"id"`
	PostID      pgtype.UUID     `json:"post_id"`
	ChunkIndex  int32           `json:"chunk_index"`
	ChunkText   string          `json:"chunk_text"`
	Embedding   pgvector.Vector `json:"embedding"`
	Slug        string          `json:"slug"`
	Title       string          `json:"title"`
	Description pgtype.Text     `json:"description"`
	Similarity  int32           `json:"similarity"`
}

func (q *Queries) SearchSimilarEmbeddingsByCategory(ctx context.Context, arg SearchSimilarEmbeddingsByCategoryParams) ([]SearchSimilarEmbeddingsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, searchSimilarEmbeddingsByCategory, arg.Embedding, arg.Categories, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchSimilarEmbeddingsByCategoryRow{}
	for rows.Next() {
		var i SearchSimilarEmbeddingsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ChunkIndex,
			&i.ChunkText,
			&i.Embedding,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
