// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: embedding_jobs.sql

package postdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmbeddingJob = `-- name: CreateEmbeddingJob :one
INSERT INTO embedding_jobs (post_id, status, chunks_total)
VALUES ($1, 'pending', $2)
RETURNING id, post_id, status, error, chunks_total, chunks_completed, created_at, started_at, completed_at
`

type CreateEmbeddingJobParams struct {
	PostID      pgtype.UUID `json:"post_id"`
	ChunksTotal pgtype.Int4 `json:"chunks_total"`
}

func (q *Queries) CreateEmbeddingJob(ctx context.Context, arg CreateEmbeddingJobParams) (EmbeddingJob, error) {
	row := q.db.QueryRow(ctx, createEmbeddingJob, arg.PostID, arg.ChunksTotal)
	var i EmbeddingJob
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Status,
		&i.Error,
		&i.ChunksTotal,
		&i.ChunksCompleted,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getEmbeddingJobByID = `-- name: GetEmbeddingJobByID :one
SELECT id, post_id, status, error, chunks_total, chunks_completed, created_at, started_at, completed_at
FROM embedding_jobs
WHERE id = $1
`

func (q *Queries) GetEmbeddingJobByID(ctx context.Context, id pgtype.UUID) (EmbeddingJob, error) {
	row := q.db.QueryRow(ctx, getEmbeddingJobByID, id)
	var i EmbeddingJob
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Status,
		&i.Error,
		&i.ChunksTotal,
		&i.ChunksCompleted,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getEmbeddingJobsByPostID = `-- name: GetEmbeddingJobsByPostID :many
SELECT id, post_id, status, error, chunks_total, chunks_completed, created_at, started_at, completed_at
FROM embedding_jobs
WHERE post_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetEmbeddingJobsByPostID(ctx context.Context, postID pgtype.UUID) ([]EmbeddingJob, error) {
	rows, err := q.db.Query(ctx, getEmbeddingJobsByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmbeddingJob{}
	for rows.Next() {
		var i EmbeddingJob
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.Status,
			&i.Error,
			&i.ChunksTotal,
			&i.ChunksCompleted,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestEmbeddingJobForPost = `-- name: GetLatestEmbeddingJobForPost :one
SELECT id, post_id, status, error, chunks_total, chunks_completed, created_at, started_at, completed_at
FROM embedding_jobs
WHERE post_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestEmbeddingJobForPost(ctx context.Context, postID pgtype.UUID) (EmbeddingJob, error) {
	row := q.db.QueryRow(ctx, getLatestEmbeddingJobForPost, postID)
	var i EmbeddingJob
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Status,
		&i.Error,
		&i.ChunksTotal,
		&i.ChunksCompleted,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getPendingEmbeddingJobs = `-- name: GetPendingEmbeddingJobs :many
SELECT id, post_id, status, error, chunks_total, chunks_completed, created_at, started_at, completed_at
FROM embedding_jobs
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetPendingEmbeddingJobs(ctx context.Context, limit int32) ([]EmbeddingJob, error) {
	rows, err := q.db.Query(ctx, getPendingEmbeddingJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmbeddingJob{}
	for rows.Next() {
		var i EmbeddingJob
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.Status,
			&i.Error,
			&i.ChunksTotal,
			&i.ChunksCompleted,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmbeddingJobProgress = `-- name: UpdateEmbeddingJobProgress :exec
UPDATE embedding_jobs
SET chunks_completed = $2
WHERE id = $1
`

type UpdateEmbeddingJobProgressParams struct {
	ID              pgtype.UUID `json:"id"`
	ChunksCompleted pgtype.Int4 `json:"chunks_completed"`
}

func (q *Queries) UpdateEmbeddingJobProgress(ctx context.Context, arg UpdateEmbeddingJobProgressParams) error {
	_, err := q.db.Exec(ctx, updateEmbeddingJobProgress, arg.ID, arg.ChunksCompleted)
	return err
}

const updateEmbeddingJobStatus = `-- name: UpdateEmbeddingJobStatus :exec
UPDATE embedding_jobs
SET status = $2::job_status,
    error = COALESCE($3, error),
    started_at = CASE WHEN $2 = 'processing' THEN NOW() ELSE started_at END,
    completed_at = CASE WHEN $2 IN ('completed', 'failed') THEN NOW() ELSE completed_at END
WHERE id = $1
`

type UpdateEmbeddingJobStatusParams struct {
	ID      pgtype.UUID `json:"id"`
	Column2 JobStatus   `json:"column_2"`
	Error   pgtype.Text `json:"error"`
}

func (q *Queries) UpdateEmbeddingJobStatus(ctx context.Context, arg UpdateEmbeddingJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateEmbeddingJobStatus, arg.ID, arg.Column2, arg.Error)
	return err
}
