// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: embeddings.sql

package postdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const createEmbedding = `-- name: CreateEmbedding :one
INSERT INTO post_embeddings (
  post_id, chunk_index, chunk_text, embedding
) VALUES (
  $1, $2, $3, $4
) RETURNING id, post_id, chunk_index, embedding, created_at, chunk_text, search_vector
`

type CreateEmbeddingParams struct {
	PostID     pgtype.UUID     `json:"post_id"`
	ChunkIndex int32           `json:"chunk_index"`
	ChunkText  pgtype.Text     `json:"chunk_text"`
	Embedding  pgvector.Vector `json:"embedding"`
}

func (q *Queries) CreateEmbedding(ctx context.Context, arg CreateEmbeddingParams) (PostEmbedding, error) {
	row := q.db.QueryRow(ctx, createEmbedding,
		arg.PostID,
		arg.ChunkIndex,
		arg.ChunkText,
		arg.Embedding,
	)
	var i PostEmbedding
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ChunkIndex,
		&i.Embedding,
		&i.CreatedAt,
		&i.ChunkText,
		&i.SearchVector,
	)
	return i, err
}

const deleteEmbeddingsByPostID = `-- name: DeleteEmbeddingsByPostID :exec
DELETE FROM post_embeddings WHERE post_id = $1
`

func (q *Queries) DeleteEmbeddingsByPostID(ctx context.Context, postID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmbeddingsByPostID, postID)
	return err
}

const getEmbeddingByID = `-- name: GetEmbeddingByID :one
SELECT id, post_id, chunk_index, embedding
FROM post_embeddings
WHERE id = $1
`

type GetEmbeddingByIDRow struct {
	ID         pgtype.UUID     `json:"id"`
	PostID     pgtype.UUID     `json:"post_id"`
	ChunkIndex int32           `json:"chunk_index"`
	Embedding  pgvector.Vector `json:"embedding"`
}

func (q *Queries) GetEmbeddingByID(ctx context.Context, id pgtype.UUID) (GetEmbeddingByIDRow, error) {
	row := q.db.QueryRow(ctx, getEmbeddingByID, id)
	var i GetEmbeddingByIDRow
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ChunkIndex,
		&i.Embedding,
	)
	return i, err
}

const getEmbeddingsByPostID = `-- name: GetEmbeddingsByPostID :many
SELECT id, post_id, chunk_index, embedding
FROM post_embeddings
WHERE post_id = $1
ORDER BY chunk_index
`

type GetEmbeddingsByPostIDRow struct {
	ID         pgtype.UUID     `json:"id"`
	PostID     pgtype.UUID     `json:"post_id"`
	ChunkIndex int32           `json:"chunk_index"`
	Embedding  pgvector.Vector `json:"embedding"`
}

func (q *Queries) GetEmbeddingsByPostID(ctx context.Context, postID pgtype.UUID) ([]GetEmbeddingsByPostIDRow, error) {
	rows, err := q.db.Query(ctx, getEmbeddingsByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEmbeddingsByPostIDRow{}
	for rows.Next() {
		var i GetEmbeddingsByPostIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ChunkIndex,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchHybrid = `-- name: SearchHybrid :many
WITH keyword_results AS (
  SELECT 
    post_id,
    row_number() OVER (ORDER BY ts_rank_cd(search_vector, plainto_tsquery('english', $1)) DESC) as rank
  FROM post_embeddings
  WHERE search_vector @@ plainto_tsquery('english', $1)
    AND chunk_text IS NOT NULL
  ORDER BY ts_rank_cd(search_vector, plainto_tsquery('english', $1)) DESC
  LIMIT 50
),
vector_results AS (
  SELECT 
    e.post_id,
    row_number() OVER (ORDER BY e.embedding <=> $2) as rank
  FROM post_embeddings e
  ORDER BY e.embedding <=> $2
  LIMIT 50
),
combined AS (
  SELECT post_id, rank FROM keyword_results
  UNION ALL
  SELECT post_id, rank FROM vector_results
)
SELECT 
  p.id,
  p.slug,
  p.title,
  p.description,
  p.cover_url,
  p.categories,
  p.tags,
  p.featured,
  p.view_count,
  p.read_time_minutes,
  p.published_at,
  SUM(1.0 / (60.0 + combined.rank))::double precision as rrf_score
FROM combined
JOIN posts p ON p.id = combined.post_id
WHERE p.is_archived = false
GROUP BY 
  p.id, p.slug, p.title, p.description, p.cover_url,
  p.categories, p.tags, p.featured, p.view_count,
  p.read_time_minutes, p.published_at
ORDER BY rrf_score DESC
LIMIT $3
`

type SearchHybridParams struct {
	PlaintoTsquery string          `json:"plainto_tsquery"`
	Embedding      pgvector.Vector `json:"embedding"`
	Limit          int32           `json:"limit"`
}

type SearchHybridRow struct {
	ID              pgtype.UUID        `json:"id"`
	Slug            string             `json:"slug"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	CoverUrl        pgtype.Text        `json:"cover_url"`
	Categories      []string           `json:"categories"`
	Tags            []string           `json:"tags"`
	Featured        pgtype.Bool        `json:"featured"`
	ViewCount       pgtype.Int4        `json:"view_count"`
	ReadTimeMinutes pgtype.Int4        `json:"read_time_minutes"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	RrfScore        float64            `json:"rrf_score"`
}

// Hybrid search: BM25 (keyword) + vector similarity via Reciprocal Rank Fusion
// $1 = text query (plain string), $2 = query embedding vector, $3 = limit
func (q *Queries) SearchHybrid(ctx context.Context, arg SearchHybridParams) ([]SearchHybridRow, error) {
	rows, err := q.db.Query(ctx, searchHybrid, arg.PlaintoTsquery, arg.Embedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchHybridRow{}
	for rows.Next() {
		var i SearchHybridRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.CoverUrl,
			&i.Categories,
			&i.Tags,
			&i.Featured,
			&i.ViewCount,
			&i.ReadTimeMinutes,
			&i.PublishedAt,
			&i.RrfScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSimilarEmbeddings = `-- name: SearchSimilarEmbeddings :many
SELECT 
  e.id,
  e.post_id,
  e.chunk_index,
  e.embedding,
  p.slug,
  p.title,
  p.description,
  (1 - (e.embedding <=> $1))::double precision as similarity
FROM post_embeddings e
JOIN posts p ON p.id = e.post_id
WHERE p.is_archived = false
ORDER BY e.embedding <=> $1
LIMIT $2
`

type SearchSimilarEmbeddingsParams struct {
	Embedding pgvector.Vector `json:"embedding"`
	Limit     int32           `json:"limit"`
}

type SearchSimilarEmbeddingsRow struct {
	ID          pgtype.UUID     `json:"id"`
	PostID      pgtype.UUID     `json:"post_id"`
	ChunkIndex  int32           `json:"chunk_index"`
	Embedding   pgvector.Vector `json:"embedding"`
	Slug        string          `json:"slug"`
	Title       string          `json:"title"`
	Description pgtype.Text     `json:"description"`
	Similarity  float64         `json:"similarity"`
}

func (q *Queries) SearchSimilarEmbeddings(ctx context.Context, arg SearchSimilarEmbeddingsParams) ([]SearchSimilarEmbeddingsRow, error) {
	rows, err := q.db.Query(ctx, searchSimilarEmbeddings, arg.Embedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchSimilarEmbeddingsRow{}
	for rows.Next() {
		var i SearchSimilarEmbeddingsRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ChunkIndex,
			&i.Embedding,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSimilarEmbeddingsByCategory = `-- name: SearchSimilarEmbeddingsByCategory :many
SELECT 
  e.id,
  e.post_id,
  e.chunk_index,
  e.embedding,
  p.slug,
  p.title,
  p.description,
  (1 - (e.embedding <=> $1))::double precision as similarity
FROM post_embeddings e
JOIN posts p ON p.id = e.post_id
WHERE p.is_archived = false 
  AND $2 = ANY(p.categories)
ORDER BY e.embedding <=> $1
LIMIT $3
`

type SearchSimilarEmbeddingsByCategoryParams struct {
	Embedding  pgvector.Vector `json:"embedding"`
	Categories []string        `json:"categories"`
	Limit      int32           `json:"limit"`
}

type SearchSimilarEmbeddingsByCategoryRow struct {
	ID          pgtype.UUID     `json:"id"`
	PostID      pgtype.UUID     `json:"post_id"`
	ChunkIndex  int32           `json:"chunk_index"`
	Embedding   pgvector.Vector `json:"embedding"`
	Slug        string          `json:"slug"`
	Title       string          `json:"title"`
	Description pgtype.Text     `json:"description"`
	Similarity  float64         `json:"similarity"`
}

func (q *Queries) SearchSimilarEmbeddingsByCategory(ctx context.Context, arg SearchSimilarEmbeddingsByCategoryParams) ([]SearchSimilarEmbeddingsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, searchSimilarEmbeddingsByCategory, arg.Embedding, arg.Categories, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchSimilarEmbeddingsByCategoryRow{}
	for rows.Next() {
		var i SearchSimilarEmbeddingsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ChunkIndex,
			&i.Embedding,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
