// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package postdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archivePost = `-- name: ArchivePost :exec
UPDATE posts SET is_archived = true, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ArchivePost(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, archivePost, id)
	return err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
  slug, title, description, content_url, categories, tags, featured, read_time_minutes, published_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, slug, title, description, content_url, categories, tags, featured, view_count, read_time_minutes, created_at, updated_at, published_at, is_archived
`

type CreatePostParams struct {
	Slug            string             `json:"slug"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	ContentUrl      string             `json:"content_url"`
	Categories      []string           `json:"categories"`
	Tags            []string           `json:"tags"`
	Featured        pgtype.Bool        `json:"featured"`
	ReadTimeMinutes pgtype.Int4        `json:"read_time_minutes"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.ContentUrl,
		arg.Categories,
		arg.Tags,
		arg.Featured,
		arg.ReadTimeMinutes,
		arg.PublishedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.ContentUrl,
		&i.Categories,
		&i.Tags,
		&i.Featured,
		&i.ViewCount,
		&i.ReadTimeMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.IsArchived,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePost, id)
	return err
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, slug, title, description, content_url, categories, tags, featured, view_count, read_time_minutes, created_at, updated_at, published_at, is_archived FROM posts
WHERE id = $1
`

func (q *Queries) GetPostByID(ctx context.Context, id pgtype.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.ContentUrl,
		&i.Categories,
		&i.Tags,
		&i.Featured,
		&i.ViewCount,
		&i.ReadTimeMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.IsArchived,
	)
	return i, err
}

const getPostBySlug = `-- name: GetPostBySlug :one
SELECT id, slug, title, description, content_url, categories, tags, featured, view_count, read_time_minutes, created_at, updated_at, published_at, is_archived FROM posts
WHERE slug = $1 AND is_archived = false
`

func (q *Queries) GetPostBySlug(ctx context.Context, slug string) (Post, error) {
	row := q.db.QueryRow(ctx, getPostBySlug, slug)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.ContentUrl,
		&i.Categories,
		&i.Tags,
		&i.Featured,
		&i.ViewCount,
		&i.ReadTimeMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.IsArchived,
	)
	return i, err
}

const getTotalPostCount = `-- name: GetTotalPostCount :one
SELECT COUNT(*) FROM posts WHERE is_archived = false
`

func (q *Queries) GetTotalPostCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalPostCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const incrementViewCount = `-- name: IncrementViewCount :exec
UPDATE posts SET view_count = view_count + 1
WHERE id = $1
`

func (q *Queries) IncrementViewCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementViewCount, id)
	return err
}

const listFeaturedPosts = `-- name: ListFeaturedPosts :many
SELECT id, slug, title, description, categories, tags, featured, view_count, read_time_minutes, published_at
FROM posts
WHERE featured = true AND is_archived = false AND published_at IS NOT NULL
ORDER BY published_at DESC
LIMIT $1
`

type ListFeaturedPostsRow struct {
	ID              pgtype.UUID        `json:"id"`
	Slug            string             `json:"slug"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	Categories      []string           `json:"categories"`
	Tags            []string           `json:"tags"`
	Featured        pgtype.Bool        `json:"featured"`
	ViewCount       pgtype.Int4        `json:"view_count"`
	ReadTimeMinutes pgtype.Int4        `json:"read_time_minutes"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) ListFeaturedPosts(ctx context.Context, limit int32) ([]ListFeaturedPostsRow, error) {
	rows, err := q.db.Query(ctx, listFeaturedPosts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeaturedPostsRow{}
	for rows.Next() {
		var i ListFeaturedPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Categories,
			&i.Tags,
			&i.Featured,
			&i.ViewCount,
			&i.ReadTimeMinutes,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPosts = `-- name: ListPosts :many
SELECT id, slug, title, description, categories, tags, featured, view_count, read_time_minutes, published_at
FROM posts
WHERE is_archived = false
ORDER BY published_at DESC NULLS LAST, created_at DESC
LIMIT $1 OFFSET $2
`

type ListPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPostsRow struct {
	ID              pgtype.UUID        `json:"id"`
	Slug            string             `json:"slug"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	Categories      []string           `json:"categories"`
	Tags            []string           `json:"tags"`
	Featured        pgtype.Bool        `json:"featured"`
	ViewCount       pgtype.Int4        `json:"view_count"`
	ReadTimeMinutes pgtype.Int4        `json:"read_time_minutes"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]ListPostsRow, error) {
	rows, err := q.db.Query(ctx, listPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsRow{}
	for rows.Next() {
		var i ListPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Categories,
			&i.Tags,
			&i.Featured,
			&i.ViewCount,
			&i.ReadTimeMinutes,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByCategory = `-- name: ListPostsByCategory :many
SELECT id, slug, title, description, categories, tags, featured, view_count, read_time_minutes, published_at
FROM posts
WHERE $1 = ANY(categories) AND is_archived = false AND published_at IS NOT NULL
ORDER BY published_at DESC
LIMIT $2 OFFSET $3
`

type ListPostsByCategoryParams struct {
	Categories []string `json:"categories"`
	Limit      int32    `json:"limit"`
	Offset     int32    `json:"offset"`
}

type ListPostsByCategoryRow struct {
	ID              pgtype.UUID        `json:"id"`
	Slug            string             `json:"slug"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	Categories      []string           `json:"categories"`
	Tags            []string           `json:"tags"`
	Featured        pgtype.Bool        `json:"featured"`
	ViewCount       pgtype.Int4        `json:"view_count"`
	ReadTimeMinutes pgtype.Int4        `json:"read_time_minutes"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) ListPostsByCategory(ctx context.Context, arg ListPostsByCategoryParams) ([]ListPostsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, listPostsByCategory, arg.Categories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsByCategoryRow{}
	for rows.Next() {
		var i ListPostsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Categories,
			&i.Tags,
			&i.Featured,
			&i.ViewCount,
			&i.ReadTimeMinutes,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByTag = `-- name: ListPostsByTag :many
SELECT id, slug, title, description, categories, tags, featured, view_count, read_time_minutes, published_at
FROM posts
WHERE $1 = ANY(tags) AND is_archived = false AND published_at IS NOT NULL
ORDER BY published_at DESC
LIMIT $2 OFFSET $3
`

type ListPostsByTagParams struct {
	Tags   []string `json:"tags"`
	Limit  int32    `json:"limit"`
	Offset int32    `json:"offset"`
}

type ListPostsByTagRow struct {
	ID              pgtype.UUID        `json:"id"`
	Slug            string             `json:"slug"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	Categories      []string           `json:"categories"`
	Tags            []string           `json:"tags"`
	Featured        pgtype.Bool        `json:"featured"`
	ViewCount       pgtype.Int4        `json:"view_count"`
	ReadTimeMinutes pgtype.Int4        `json:"read_time_minutes"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) ListPostsByTag(ctx context.Context, arg ListPostsByTagParams) ([]ListPostsByTagRow, error) {
	rows, err := q.db.Query(ctx, listPostsByTag, arg.Tags, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsByTagRow{}
	for rows.Next() {
		var i ListPostsByTagRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Categories,
			&i.Tags,
			&i.Featured,
			&i.ViewCount,
			&i.ReadTimeMinutes,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPosts = `-- name: SearchPosts :many
SELECT id, slug, title, description, categories, tags, featured, view_count, read_time_minutes, published_at
FROM posts
WHERE 
  (title ILIKE '%' || $1 || '%' OR description ILIKE '%' || $1 || '%')
  AND is_archived = false 
  AND published_at IS NOT NULL
ORDER BY published_at DESC
LIMIT $2 OFFSET $3
`

type SearchPostsParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type SearchPostsRow struct {
	ID              pgtype.UUID        `json:"id"`
	Slug            string             `json:"slug"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	Categories      []string           `json:"categories"`
	Tags            []string           `json:"tags"`
	Featured        pgtype.Bool        `json:"featured"`
	ViewCount       pgtype.Int4        `json:"view_count"`
	ReadTimeMinutes pgtype.Int4        `json:"read_time_minutes"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) SearchPosts(ctx context.Context, arg SearchPostsParams) ([]SearchPostsRow, error) {
	rows, err := q.db.Query(ctx, searchPosts, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPostsRow{}
	for rows.Next() {
		var i SearchPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Categories,
			&i.Tags,
			&i.Featured,
			&i.ViewCount,
			&i.ReadTimeMinutes,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts SET
  title = COALESCE($2, title),
  description = COALESCE($3, description),
  content_url = COALESCE($4, content_url),
  categories = COALESCE($5, categories),
  tags = COALESCE($6, tags),
  featured = COALESCE($7, featured),
  read_time_minutes = COALESCE($8, read_time_minutes),
  published_at = COALESCE($9, published_at),
  is_archived = COALESCE($10, is_archived),
  updated_at = NOW()
WHERE id = $1
RETURNING id, slug, title, description, content_url, categories, tags, featured, view_count, read_time_minutes, created_at, updated_at, published_at, is_archived
`

type UpdatePostParams struct {
	ID              pgtype.UUID        `json:"id"`
	Title           pgtype.Text        `json:"title"`
	Description     pgtype.Text        `json:"description"`
	ContentUrl      pgtype.Text        `json:"content_url"`
	Categories      []string           `json:"categories"`
	Tags            []string           `json:"tags"`
	Featured        pgtype.Bool        `json:"featured"`
	ReadTimeMinutes pgtype.Int4        `json:"read_time_minutes"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	IsArchived      pgtype.Bool        `json:"is_archived"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.ContentUrl,
		arg.Categories,
		arg.Tags,
		arg.Featured,
		arg.ReadTimeMinutes,
		arg.PublishedAt,
		arg.IsArchived,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.ContentUrl,
		&i.Categories,
		&i.Tags,
		&i.Featured,
		&i.ViewCount,
		&i.ReadTimeMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.IsArchived,
	)
	return i, err
}
